name: build

on: [push, pull_request]

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '2.7', '3.5', '3.6', '3.7', '3.8', 'pypy2', 'pypy3' ]
    steps:
      - uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies  
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-benchmark enum34 numpy arrow ruamel.yaml
      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:`pwd`
          py.test tests/ --benchmark-disable --showlocals --verbose
  deploy:
    name: Build and Publish into PyPI
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Build package
        run: python setup.py sdist
      - name: Publish package
        # FIXME update to stable release when it will be ready
        uses: pypa/gh-action-pypi-publish@74be6d3
        with:
          password: ${{ secrets.pypi_password }}

