name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [ '3.6', '3.7', '3.8', '3.9', '3.10', 'pypy3' ]
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies  
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-benchmark enum34 numpy arrow ruamel.yaml cloudpickle lz4
      - name: Run tests
        run: |
          py.test tests/ --benchmark-disable --showlocals --verbose

  create_wheel_and_sdist:
    name: Build binary and source archives
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build twine pip setuptools wheel
      - name: Build wheel and sdist
        run: |
          python setup.py sdist bdist_wheel
          twine check dist/*
      - name: Collect built archives
        uses: actions/upload-artifact@v2
        with:
          path: dist/*
